# Change these first
owner: compusam # Your GitHub username
repo: upckmonitor # Your Github repository name

# Add your sites here
sites:
  - name: 100diasdeverano
    url: https://100diasdeverano.com/
  - name: Agristarcontigo
    url: https://agristarcontigo.com/

status-website:
  baseUrl: /upckmonitor
  apiBaseUrl: https://api.github.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: UpptimeCheckMonitor
  introTitle: "**Upptime** for check and monitor websites."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
