# Change these first
owner: compusam # Your GitHub username
repo: upckmonitor # Your Github repository name

# Add your sites here
sites:
  - name: 100diasdeverano
    url: https://100diasdeverano.com
  - name: Agristarcontigo
    url: https://agristarcontigo.com
  - name: CelebraconCRE
    url: https://celebraconcre.com
  - name: Cinemalth
    url: https://cinemalth.com
  - name: Cinemalth
    url: https://cinemalth.com.mx
  - name: CircuitoCampeones
    url: https://circuitocampeones.com.mx
  - name: Circulodehonorapp
    url: https://circulodehonorapp.com
  - name: Clubdeganadoresmayoreo
    url: https://clubdeganadoresmayoreo.com
  - name: Clubdesocios
    url: https://clubdesociospepsico.com.mx
  - name: CNV
    url: https://circulodehonorpepsico.com
  - name: Compartamostepremia
    url: https://compartamostepremia.com
  - name: Conexionescollins
    url: https://conexionescollins.com
  - name: Contpaqistore
    url: https://contpaqistore.com
  - name: DbaRewards
    url: https://dbarewards.com
  - name: DesafioPepsico
    url: https://desafiopepsico.com
  - name: Diageobaracademy
    url: https://diageobaracademymexico.com
  - name: Enlacechopo
    url: https://enlacechopo.com.mx
  - name: Erewardsmx
    url: https://erewardsmx.com 
  - name: GMF
    url: https://clubroyalelite.com  
  - name: Honorpremia
    url: https://honorpremia.com  
  - name: Jacto
    url: https://jactopremios.com  
  - name: Liberatubelleza
    url: https://liberatubelleza.com.mx
  - name: Lidereshell
    url: https://liderescs.com.mx
  - name: Lubechampions
    url: https://lubechampions.com.mx
  - name: Mayre
    url: https://recompensasmayre.com  
  - name: Motivale
    url: https://motivale.com  
  - name: Premianavidad
    url: https://premianavidadpepsico.com  
  - name: Programaclubdeganadores
    url: https://programaclubdeganadores.com  
  - name: Programapremianavidad
    url: https://programapremianavidad.com
  - name: Programasocioestrella
    url: https://programasocioestrella.com  
  - name: Promoshopclarios
    url: https://promoshopclarios.com.mx
  - name: Raisingthebar
    url: https://raisingthebarmexico.mx
  - name: Recibetucodigo
    url: https://recibetucodigo.com
  - name: Recompensamostulealtad
    url: https://recompensamostulealtad.com
  - name: Redrewards
    url: https://redrewards.mx
  - name: SocioPepsico
    url: https://sociopepsicomexico.com
  - name: Spionline
    url: https://spi-online.com
  - name: SuperacionJD
    url: https://superacionjd.com
  - name: Urreapremia
    url: https://urreapremia.com
status-website:
  baseUrl: /upckmonitor
  apiBaseUrl: https://api.github.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: UpptimeCheckMonitor
  introTitle: "**Upptime** for check and monitor websites."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
